
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import ConditionalLayout from "@/components/conditionalLayout";
import { UserProvider } from "@/context/UserContext";
import Script from "next/script";




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  

  return (
    <html lang="en">
      <head>
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive"
          />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* { <Navbar/>}
        <Toaster position="top-center"/>
        {children}
        { <Footer/>} */}
<UserProvider>
  <Toaster position="top-center" />
<ConditionalLayout>{children}</ConditionalLayout>
</UserProvider>
      </body>
    </html>
  );
}
